### ISSUE TITLE
Unable to use adaptivecards-reactnative with yarn due to `patch-package`

### ISSUE THREAD

**Issue by chrisglein** [BigThinkcode/AdaptiveCards#115]
# Platform

* UWP

(although it doesn't get that far - this is failing on adding to a project)

# Author or host

Host

# Version of SDK

2.2.32

# Issue

After doing a `yarn add adaptivecards-reactnative` to a project, `yarn` produces errors:
```cmd
> yarn
yarn install v1.22.19
[1/4] Resolving packages...
warning adaptivecards-reactnative > react-native-video > shaka-player@2.5.23: Shaka Player < v3.2 is no longer supported.
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error C:\Users\redacted\source\artificial-chat\node_modules\adaptivecards-reactnative: Command failed.
Exit code: 1
Command: patch-package
Arguments:
Directory: C:\Users\redacted\source\artificial-chat\node_modules\adaptivecards-reactnative
Output:
'patch-package' is not recognized as an internal or external command,
operable program or batch file.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

The [docs](https://learn.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/react-native/getting-started) don't explicitly call out yarn, but generally yarn is [expected to work](https://reactnative.dev/docs/libraries#selecting-a-package-manager) with RN projects.

Seems to be directly called out as a devDependency (incorrectly?): https://github.com/BigThinkcode/AdaptiveCards/blob/fork-main/source/community/reactnative/package.json#L50

**Comment by chrisglein** [comment]
FYI @BigThinkcode it looks like you have labeling workflows for triage that are failing:

> .github/workflows/new-issues.yaml: All jobs have failed
> .github/workflows/new-issues.yaml / Assign new issue to Triage Needed [3](https://github.com/BigThinkcode/AdaptiveCards/actions/runs/4207160729)
Failed in 3 seconds

> [Assign new issue to Triage Needed](https://github.com/BigThinkcode/AdaptiveCards/actions/runs/4207160729/jobs/7301602797#step:2:9)
Cannot read property 'id' of undefined

**Comment by chiaramooney** [comment]
Wtih the devDep specification yarn will only install patch-package when you are developing on the module. In the case of adding adaptive cards to an RNW app, patch-package will not install unless it is listed as a dependency or peerDependency.

**Comment by chrisglein** [comment]
Additionally, it seems like the one patch (for react-native-video) is out of date and has a conflict:
```
patch-package 6.5.1
Applying patches...

**ERROR** Failed to apply patch for package react-native-video at path

    node_modules/react-native-video

  This error was caused because react-native-video has changed since you
  made the patch file for it. This introduced conflicts with your patch,
  just like a merge conflict in Git when separate incompatible changes are
  made to the same piece of code.

  Maybe this means your patch file is no longer necessary, in which case
  hooray! Just delete it!

  Otherwise, you need to generate a new patch file.

  To generate a new one, just repeat the steps you made to generate the first
  one.

  i.e. manually make the appropriate file changes, then run

    patch-package react-native-video

  Info:
    Patch file: patches/react-native-video+5.2.0.patch
    Patch was made for version: 5.2.0
    Installed version: 5.2.1

---
patch-package finished with 1 error(s).
Done in 113.41s.
```
Change that added the patch file was this one: https://github.com/BigThinkcode/AdaptiveCards/commit/af246b3365fa6e2a8515e76e1b1198ff9d8edd2e#diff-a1792d0b1c17aaf3fd7598873390eaf1a8805a7d9f9506cc73ca139ff44dec14
But I haven't yet found discussion of why the patch was made or link to an issue.

**Comment by chrisglein** [comment]
Removing the patch resolves the issue. Lacking any information on why that patch was made, that seems like the most reasonable solution. I'll submit a PR.
